// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Formplug","status":true,"description":"Allows users to give a thumbs up, down or Wiggle to Formbar and interact with Formbar API via socket.io-client.","parameters":{"Formbar URL":"https://formbeta.yorktechapps.com/","API Key":"fdce342c804e6f9e9dbce61a27ce7427677f65c1b7ea55ce1a2f609f04eb5d163bc9834e02329ca58873cc49d31922c5ff0501f0f42d49dd9e363005fa469deb"}}
];
